motd=§bServidor Crossplay §7| §fJava + Bedrock
gamemode=survival
difficulty=normal
max-players=10
view-distance=8
simulation-distance=6
spawn-protection=0
server-port=25565
server-ip=
online-mode=true
pvp=true
white-list=false
enforce-whitelist=false
level-name=world
